"""board_recorder 録画ユニバースの生成 (_bellwether の同名スクリプトを本リポへ再移植)。

選定規則 (board_recorder_universe.txt ヘッダの正本規則):
  - S:/jp/stocks_daily/<code>.duckdb の各銘柄について、直近 20 営業日の
    売買代金 median(Close*Volume) で降順ランキング (Volume>0・Close>0 の日のみ)。
  - 上位 40 銘柄 = liquid tier。7203 (トヨタ) を必ず liquid に含める。
  - mid tier (rank200-250 帯 ×10) は agree_biggap 共存契約
    (register 50 枠 = 板読み 40 / agree_biggap 10・2026-07-16 owner 承認) により
    **既定で停止**。--include-mid で 50 銘柄構成を再生成できる (共存解消時のみ)。

運用 (docs/nightly-retrain-runbook.md):
  - 既定は **提案モード**: scripts/board_recorder_universe_next.txt へ書き、現行との
    差分 (added/removed) を表示するだけ。現行ファイルは変更しない。
  - 明示 --apply でのみ board_recorder_universe.txt を原子的に置換する。
  - nightly job からは呼ばない (手動判断)。理由: (1) register 銘柄の継続性 — 無断入替は
    録画カバレッジと current_registered.json 契約 (agree_biggap の解除禁止リスト) を壊す、
    (2) 50 枠共存契約の配分は owner 判断事項。

usage: uv run python scripts/build_board_universe.py [--apply] [--include-mid]
       [--out PATH] (env STOCKS_DAILY_DIR で日足ディレクトリを上書き可)
"""
from __future__ import annotations

import argparse
import glob
import os
import sys
from datetime import datetime
from pathlib import Path

import duckdb

try:  # Windows console 既定 cp932 対策 (runner.py と同じ)
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

STOCKS_DAILY_DIR = os.environ.get("STOCKS_DAILY_DIR", r"S:/jp/stocks_daily")
SCRIPTS_DIR = Path(__file__).resolve().parent
CURRENT_PATH = SCRIPTS_DIR / "board_recorder_universe.txt"
PROPOSAL_PATH = SCRIPTS_DIR / "board_recorder_universe_next.txt"

N_LIQUID = 40
MID_BAND = (200, 250)  # 1-based inclusive rank band
N_MID = 10
MUST_INCLUDE = ["7203"]
MIN_DAYS = 5  # 直近 20 営業日窓のうち最低必要な有効日数 (原実装と同じ)

MEDIAN_SQL = """
WITH day AS (
    SELECT CAST(Date AS DATE) AS d, max(Close) AS c, max(Volume) AS v
    FROM stocks_daily
    WHERE Volume > 0 AND Close > 0 AND Date >= DATE '2000-01-01'
    GROUP BY CAST(Date AS DATE)
), last20 AS (
    SELECT c * v AS tv FROM day ORDER BY d DESC LIMIT 20
)
SELECT median(tv) AS med, count(*) AS n FROM last20
"""


def scan_ranking(daily_dir: str) -> list[tuple[str, float, int]]:
    files = sorted(glob.glob(os.path.join(daily_dir, "*.duckdb")))
    if not files:
        raise SystemExit(f"no duckdb files under {daily_dir}")
    print(f"scanning {len(files)} files under {daily_dir} ...", flush=True)
    rows: list[tuple[str, float, int]] = []
    for i, f in enumerate(files):
        code = os.path.splitext(os.path.basename(f))[0]
        try:
            con = duckdb.connect(f, read_only=True)
            med, n = con.execute(MEDIAN_SQL).fetchone()
            con.close()
        except Exception:
            continue  # 壊れた/ロック中のファイルは黙って除外 (原実装と同じ)
        if med is None or n is None or n < MIN_DAYS:
            continue
        rows.append((code, float(med), int(n)))
        if (i + 1) % 500 == 0:
            print(f"  ...{i + 1}/{len(files)} scanned, {len(rows)} usable", flush=True)
    rows.sort(key=lambda r: r[1], reverse=True)
    print(f"usable codes: {len(rows)}", flush=True)
    return rows


def select_universe(rows, include_mid: bool) -> list[tuple[str, str]]:
    rank = {code: idx + 1 for idx, (code, _, _) in enumerate(rows)}
    selected: list[tuple[str, str]] = []
    seen: set[str] = set()
    for code, _med, _n in rows[:N_LIQUID]:
        selected.append((code, "liquid"))
        seen.add(code)
    for code in MUST_INCLUDE:
        if code not in seen:
            selected.append((code, "liquid"))
            seen.add(code)
            print(f"  force-added {code} to liquid (natural rank={rank.get(code, 'N/A')})")
    # liquid は必ず N_LIQUID 本に丸める (must-include で溢れた分は最下位を落とす)
    liquid = [c for c, t in selected if t == "liquid"]
    if len(liquid) > N_LIQUID:
        drop = [c for c in liquid if c not in MUST_INCLUDE][N_LIQUID - len(MUST_INCLUDE):]
        selected = [(c, t) for c, t in selected if c not in drop]
        print(f"  cap {N_LIQUID}: dropped {drop}")
    if include_mid:
        lo, hi = MID_BAND
        band = [r for r in rows[lo - 1:hi] if r[0] not in seen]
        for code, _med, _n in band[:N_MID]:
            selected.append((code, "mid"))
            seen.add(code)
    return selected


def render(selected: list[tuple[str, str]], include_mid: bool) -> str:
    lines = [
        "# board_recorder universe (auto-generated by build_board_universe.py)",
        f"# rule: liquid=top{N_LIQUID} by median(Close*Volume) of last 20 sessions; "
        f"mid=rank{MID_BAND[0]}-{MID_BAND[1]} band x{N_MID}; must-include={MUST_INCLUDE}",
        "# columns: code<TAB>tier",
    ]
    if not include_mid:
        lines += [
            "# 2026-07-16 owner 承認: agree_biggap 共存契約 (register 50 枠 = 板読み 40 / "
            "agree_biggap 10)",
            "# のため mid tier は停止中。共存解消時は build_board_universe.py --include-mid で",
            "# 50 銘柄構成に再生成してよい。",
        ]
    lines.append(f"# generated: {datetime.now().isoformat(timespec='seconds')}")
    lines += [f"{code}\t{tier}" for code, tier in selected]
    return "\n".join(lines) + "\n"


def read_current(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    out = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.replace(",", "\t").split("\t")
        out[parts[0].strip()] = parts[1].strip() if len(parts) > 1 else "unknown"
    return out


def diff_report(current: dict[str, str], selected: list[tuple[str, str]]) -> None:
    # code の大文字小文字はファイル名由来で揺れる (285a 等) — 比較は case-insensitive
    current = {c.upper(): t for c, t in current.items()}
    new = {c.upper(): t for c, t in selected}
    added = sorted(set(new) - set(current))
    removed = sorted(set(current) - set(new))
    kept = sorted(set(current) & set(new))
    print("---- diff vs current board_recorder_universe.txt ----")
    print(f"kept   : {len(kept)}")
    print(f"added  : {len(added)} {added}")
    print(f"removed: {len(removed)} {removed}")
    retier = [c for c in kept if current[c] != new[c]]
    if retier:
        print(f"tier changed: {[(c, current[c], new[c]) for c in retier]}")


def main() -> int:
    ap = argparse.ArgumentParser(
        description="板読み録画ユニバース生成 (既定=提案のみ。--apply で置換。nightly からは呼ばない)")
    ap.add_argument("--apply", action="store_true",
                    help="board_recorder_universe.txt を原子的に置換 (手動判断のみ)")
    ap.add_argument("--include-mid", action="store_true",
                    help="mid tier 10 銘柄も生成 (共存契約解消時のみ・50 銘柄構成)")
    ap.add_argument("--out", default=str(PROPOSAL_PATH),
                    help="提案ファイルの出力先 (既定 scripts/board_recorder_universe_next.txt)")
    args = ap.parse_args()

    rows = scan_ranking(STOCKS_DAILY_DIR)
    selected = select_universe(rows, args.include_mid)
    text = render(selected, args.include_mid)

    out_path = Path(args.out)
    out_path.write_text(text, encoding="utf-8", newline="\n")
    n_liq = sum(1 for _, t in selected if t == "liquid")
    n_mid = sum(1 for _, t in selected if t == "mid")
    print(f"proposal written: {out_path} ({len(selected)} codes: "
          f"liquid={n_liq}, mid={n_mid})")
    diff_report(read_current(CURRENT_PATH), selected)

    if args.apply:
        tmp = CURRENT_PATH.with_suffix(".txt.tmp")
        tmp.write_text(text, encoding="utf-8", newline="\n")
        os.replace(tmp, CURRENT_PATH)
        print(f"APPLIED: {CURRENT_PATH} を置換した (register 継続性に注意 — "
              "翌朝のランタイム再起動で新 universe が register される)")
    else:
        print("NOT applied (提案のみ)。置換するには --apply を明示すること。")
    return 0


if __name__ == "__main__":
    sys.exit(main())
